### ISSUE TITLE
[Question]: How to use secret management?

### ISSUE THREAD

**Issue by tom-tubeless** [tiredofit/home#1]
# Question
hey @tiredofit. Great configuration that you crafted there.
I am using NixOS for a while now and your repo convinced me, that it is time for the next step.
I am intrigued by the idea of using the script for administering my machine configurations.

My problem start with secret managing. It is not the first time I failed to implement sops-nix in my configuration.
I tried your repo, added a new host and with a new age-keypair I was ready to go.
As I understand, your scripts copies over the host-keys to generate the secrets.
I have the public ssh-host-key for my target system under the host/secret directory.  Also in the ssh-configuration of the script I inserted the path of the according secret ssh-host-key.

I always get 
```
sops-install-secrets: Imported /persist/etc/ssh/ssh_host_ed25519_key as age key with fingerprint age1g85r5cqldg9hrz3n6rmwz8e40x8wqrw5r6uxs54ecswpu4nzt3ls83ltfc
/nix/store/0igfrca140rvyiry2wxdvx2pqdw2rzdd-sops-install-secrets-0.0.1/bin/sops-install-secrets: Failed to decrypt '/nix/store/dg5szfgaaqlq2knh7rc1sfcclwqpjja3-secrets.yaml': Error getting data key: 0 successful groups required, got 0
Activation script snippet 'setupSecretsForUsers' failed (1)
```
That goes for user and system secret creation.

It would be much appreciated if you could help me solving this problem. What am I misunderstanding? By the way your notes already helped a lot in understanding the usage of NixOS.

Best regards

lgo

**Comment by tiredofit** [comment]
Hi Igo, 

Neat, who would have thought my summer of 2023 would be of use to others!

You are correct, when using the script it:

- Generates a SSH Host Key pair and uses that to unlock the secrets for the host.
- For users, which is a part of the home-manager repo (this one) there is no script and it relies on some sort of key pair with the private keys sitting in by line at `~/.config/sops/age/keys.txt`

My guess, is that your `.sops.yaml` is the culprit. Are you able at all to perform from your own user `sops hosts/common/secrets/secrets.yaml`  - If it doesn't load your editor with the secret of `common: Common Example Secret` as the contents, you should key some sort of private/public keypair generated on your end for your user and insert it in to the `.sops.yaml` file and under all the hosts key_groups.

I remember having some problems with this very thing and realized I had the wrong public keys in my configuration file for the longest time. Once thats in place this seemingly just "work", but that may be masked by my own memories, you simply could be descending into my own madness :)

**Comment by tom-tubeless** [comment]
Hi @tiredofit,
I am surprised, that your repo is not getting more attention. It is really thought through and pragmatic in the best way.

I agree with your assertion of suspecting `.sops.yaml`. Here is my journey into your 'maze of madness':

After deleting your hosts and generating a new one, fitting to my test/target machine, I generated an age keypair:
```
mkdir -p ~/.config/sops/age
age-keygen -o ~/.config/sops/age/keys.txt
```
... and exported the age key:
```
age-keygen -y ~/.config/sops/age/keys.txt
```
After adding it to my `.sops.yaml` and generated new secrets:
```
sops hosts/common/secret/secret.yaml
sops users/secrets.yaml
```
I filled it according to your example. By the way should the secret in the file be embraced by `"`?

After this I felt equipped to descent into your mad dungeon and started a new Installation.
It formatted my disk and copied over the nix-closure.
But than the monsters appeared behind the corner of `### Copying extra files ###`.
After setting up the bootloader I got:
```
setting up secrets for users...
sops-install-secrets: Imported /persist/etc/ssh/ssh_host_ed25519_key as age key with fingerprint age1v0rldr2nllz8qdtamk9mh9xhzvljjamvhea8dxsajnm7w69fff3sxpp8tw
/nix/store/0igfrca140rvyiry2wxdvx2pqdw2rzdd-sops-install-secrets-0.0.1/bin/sops-install-secrets: Failed to decrypt '/nix/store/d6hqzpqszha4a2k32mf5rz4g98sazcka-secrets.yaml': Error getting data key: 0 successful groups required, got 0
Activation script snippet 'setupSecretsForUsers' failed (1)
warning: password file ‘/run/secrets-for-users/root-password’ does not exist
```

After setting up the `/etc` directoy I got:
```
sops-install-secrets: Imported /persist/etc/ssh/ssh_host_ed25519_key as age key with fingerprint age1v0rldr2nllz8qdtamk9mh9xhzvljjamvhea8dxsajnm7w69fff3sxpp8tw
/nix/store/0igfrca140rvyiry2wxdvx2pqdw2rzdd-sops-install-secrets-0.0.1/bin/sops-install-secrets: Failed to decrypt '/nix/store/z55qhsr6yxrssgxdkcqy53zlpsnz7hl9-secrets.yaml': Error getting data key: 0 successful groups required, got 0
Activation script snippet 'setupSecrets' failed (1)
Setting up sops templates...
Traceback (most recent call last):
  File "/nix/store/0xkph1sa4xda8nsqq2yn82cbpqq8lq39-substitute", line 26, in <module>
    main()
  File "/nix/store/0xkph1sa4xda8nsqq2yn82cbpqq8lq39-substitute", line 23, in main
    print(substitute(target, subst))
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/0xkph1sa4xda8nsqq2yn82cbpqq8lq39-substitute", line 14, in substitute
    with open(path) as f:
         ^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/run/secrets/common'
Activation script snippet 'renderSecrets' failed (1)
usage: nvd diff [-h] root1 root2
nvd diff: error: the following arguments are required: root2
usage: nvd diff [-h] root1 root2
nvd diff: error: the following arguments are required: root2
Activation script snippet 'report-changes' failed (2)
```

Funny fact: After the script `hosts/flores/secrets/secrets.yaml` is generated but I cannot decrypt it. The same goes for the other secrets I could decrypt before running the script.
```
Recovery failed because no master key was able to decrypt the file. In
order for SOPS to recover the file, at least one key has to be successful,
but none were.
```

If you got the time I welcome you to shed some light into this dark corner of your dungeon and fight by my side with your sword of knowledge.

**Comment by tom-tubeless** [comment]
Sorry,
I just realized, that I issued in the wrong repo. It was meant to be in your nixos-config.
